### ISSUE TITLE
Python flask-classful problem, FlaskView.register not calling my class's __init__ correctly

### ISSUE THREAD

**Issue by push-22** [pallets-eco/flask-classful#142] opened 2022-04-12 14:46 UTC
The example straight from the docs here: http://flask-classful.teracy.org/#well-more-words-on-register doesn't work.

when run I get the error:

> TypeError: QuotesView.__init__() missing 1 required positional argument: 'my_init_argument'

```
I'm using python 3.10.2 and "pip install flask-classful -U" gives:
Requirement already satisfied: flask-classful in c:\program files\python310\lib\site-packages (0.14.2) Requirement already satisfied: Flask!=0.12.3,>=0.11 in c:\program files\python310\lib\site-packages (from flask-classful) (2.1.1) Requirement already satisfied: Werkzeug>=2.0 in c:\program files\python310\lib\site-packages (from Flask!=0.12.3,>=0.11->flask-classful) (2.1.1)
Requirement already satisfied: itsdangerous>=2.0 in c:\program files\python310\lib\site-packages (from Flask!=0.12.3,>=0.11->flask-classful) (2.1.2) Requirement already satisfied: Jinja2>=3.0 in c:\program files\python310\lib\site-packages (from Flask!=0.12.3,>=0.11->flask-classful) (3.1.1)
Requirement already satisfied: click>=8.0 in c:\program files\python310\lib\site-packages (from Flask!=0.12.3,>=0.11->flask-classful) (8.1.2)
Requirement already satisfied: colorama in c:\program files\python310\lib\site-packages (from click>=8.0->Flask!=0.12.3,>=0.11->flask-classful) (0.4.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\program files\python310\lib\site-packages (from Jinja2>=3.0->Flask!=0.12.3,>=0.11->flask-classful) (2.1.1)
```
It would appear to be a problem in flask_clasful.py make_proxy_method on line 230, where nothing is being passed into the constructor (which should have been captured in register as a class variable).

Does anyone know a fix to or a workaround for this?

Many Thanks.

**Comment by davidism** [comment] 2023-09-07 22:22
Duplicate of #130

**Closed by davidism** 2023-09-07 22:22 UTC
